const WORDS_EN = {
  3: ["the","and","you","for","but","not","all","any","can","had",
"her","was","one","our","out","day","get","has","him","his",
"how","man","new","now","old","see","two","use","way","who",
"why","are","did","may","off","say","too","top","let","put",
"big","job","yes","low","own","net","run","sun","try","fun",
"act","add","box","car","end","far","few","key","law","map",
"pay","red","set","tax","war","yet","bad","god","log","air",
"ask","via","win","yes","zip","tie","cut","eat","fix","hit",
"lay","mix","nod","pan","ram","sit","tap","van","wet","yak"],
  4: ["this","that","with","have","your","from","they","will","what","when",
"make","time","just","know","take","into","good","some","come","over",
"back","only","look","also","than","help","need","work","life","love",
"give","most","very","much","down","call","long","part","find","used",
"each","last","high","next","name","year","them","more","then","away",
"read","keep","mind","home","sure","turn","open","fact","area","kind",
"case","done","real","gone","hope","deal","feel","soon","role","view",
"line","side","free","full","hard","mean","step","move","plan","base",
"form","head","care","rate","easy","test","goal","data","note","list",
"body","face","sort","type","rule","page","show","live","join","pass"],
  5: ["about","other","which","their","there","would","these","could","every","first",
"after","where","right","think","great","again","those","never","under","small",
"place","while","found","house","world","three","group","state","still","might",
"being","often","point","large","study","times","money","water","story","young",
"thing","heart","words","power","today","early","short","class","black","white",
"given","order","level","table","light","human","sound","space","field","value",
"paper","north","south","above","below","truth","music","voice","whole","clear",
"close","break","bring","write","watch","stand","start","reach","learn","carry",
"cause","drive","build","check","cover","focus","laugh","match","prove","share",
"sleep","spend","teach","touch","visit","worry","worth","guess","enjoy","raise"],
  6: ["people","before","little","number","public","system","school","family","within","always",
"follow","around","animal","change","second","though","mother","father","friend","health",
"market","social","policy","nation","figure","office","effect","street","center","reason",
"access","course","action","period","letter","result","record","future","energy","season",
"modern","nature","window","chance","create","moment","simple","source","travel","income",
"remain","effort","summer","spring","winter","degree","growth","speech","status","memory",
"notice","safety","choice","artist","career","impact","couple","charge","bridge","county",
"object","review","manage","accept","wonder","prefer","repair","border","credit","report",
"profit","budget","volume","device","survey","motion","aspect","export","import","manual",
"access","update","submit","cancel","select","format","viewer","editor","viewer","viewer"]
};
